[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "paris"
via_ir = true

# Security-focused configuration
gas_reports = ["*"]
gas_reports_ignore = []

# OpenZeppelin remappings
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

# Security testing profile
[profile.security]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "paris"
via_ir = true
optimizer = true
optimizer_runs = 200
gas_reports = ["*"]
verbosity = 3

# Fuzz testing configuration
[fuzz]
runs = 10000
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

# Invariant testing configuration
[invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
